apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-express
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-express
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-express
    spec:
      containers:
        - env:
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: admin
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: admin
            - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
              value: root
            - name: ME_CONFIG_MONGODB_AUTH_USERNAME
              value: root
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://mongodb:32323
          image: mongo-express:latest
          name: mongo-express
          ports:
            - containerPort: 8081
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data-container
      restartPolicy: Always
      volumes:
        - name: mongodb-data-container
          persistentVolumeClaim:
            claimName: mongodb-data-container
status: {}
