version: '3.7'
services:
  mongodb:
    container_name: "db_mongo"
    image: mongo:latest
    environment:
      MONGO_INITDB_PASSWORD: root
      MONGO_INITDB_USERNAME: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    
volumes:
  mongodb_data_container: